server:
  port: 80
spring:
  kafka:
    consumer:
      bootstrap-servers: broker:29092
      group-id: group_id
      auto-offset-reset: earliest
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        ddl-auto: create
        jdbc:
          time_zone: CET
  datasource:
    url: jdbc:postgresql://postgres:5432/db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

logging:
  level:
    root: INFO